### ISSUE TITLE
insert styles

### ISSUE THREAD

**Issue by scoutrul** [ybarukh/react-cytoscape#2]
Hi! Can you help me to insert this styles into your component?
https://codepen.io/yeoupooh/pen/RrBdeZ
I just wanna try this stuff

**Comment by ybarukh** [comment]
Hi,

It's simple.

<ReactCytoscape style={your Style}... />

Bye

**Comment by scoutrul** [comment]
With the array parentless ?

**Comment by ybarukh** [comment]
First you assigned a variable for the style.

let myStyle = [{

selector: 'node',
style: {
'width': 200,
'height': 200,
'content': 'data(text)',
// 'text-opacity': 0.5,
'text-valign': 'center',
'color': 'white',
'background-color': nodeOptions.normal.bgColor,
'text-outline-width': 2,
'text-outline-color': '#222'
}
},

  {
    selector: 'edge',
    style: {
      'width': 10,
      'target-arrow-shape': 'triangle',
      'line-color': 'data(color)',
      'target-arrow-color': '#9dbaea'
    }
  },

  {
    selector: ':selected',
    style: {
      'background-color': 'yellow',
      'line-color': 'yellow',
      'target-arrow-color': 'black',
      'source-arrow-color': 'black',
    }
  },

  {
    selector: 'edge:selected',
    style: {
      'width': 20
    }
  }
]


And use it :

<ReactCytoscape style={myStyle}... />
