### ISSUE TITLE
Specify layout options

### ISSUE THREAD

**Issue by sfbrunner** [ybarukh/react-cytoscape#4]
Hi ybarukh,
Really helpful package, thanks a lot!
I was just wondering, how do you specify layout options in your setup? Ie. the Cola layout has tons of options available: https://github.com/cytoscape/cytoscape.js-cola

Thanks!
Simon

**Comment by anotherchrisatwork** [comment]
Hi @sfbrunner -- I discovered that you can just give the various options in the "layout" option, so here I've set `maxSimulationTime`:

    render() {
      return (
        <div className="App">
          <ReactCytoscape
            containerID="cy"
            elements={this.getElements()}
            cyRef={(cy) => {
              this.cyRef(cy)
            }}
            ref={this.mainBoxRef}
            cytoscapeOptions={{ wheelSensitivity: 0.1 }}
            layout={{
              name: 'cola',
              maxSimulationTime: 16000
            }}
          />
        </div>
      )
    }

**Comment by ybarukh** [comment]
Hi,
This was stated in the **README.md** file.

**Comment by anotherchrisatwork** [comment]
Hi @ybarukh -- well... not really... it just says that you can set the name, it's not (immediately) obvious that you can set any other setting there too.  Some of us need more help than others :-)

Cheers for doing react-cytoscape!

**Comment by ybarukh** [comment]
I understand, but I do not have much time for it.

This package just makes the glue between React and Cytoscape.
The code is really very simple.
Just what is needed.

In any case thank you for your use

**Comment by surfjedi** [comment]
I second this I have several variations and it appears that you can pass options in like spacingFactor etc..  It has no effect?
        <ReactCytoscape
          containerID="cy"
          // elements={this.props.elements}
          elements={elements}
          cyRef={cy => {
            this.cyRef(cy);
          }}
          style={graphStyle}
          styleContainer={{ height: '30vh' }}
          cytoscapeOptions={{ wheelSensitivity: 0.1, spacingFactor: 1.2 }}
          layout={{name: 'cola'}} // can be cola or dagre right now
        />

**Comment by surfjedi** [comment]
@anotherchrisatwork did you solve this?

**Comment by anotherchrisatwork** [comment]
@surfjedi Only for the `layout` setting.
